-- CodeEcho / SWE Interview Prep — Supabase schema
-- Auth is Supabase Auth. user_id columns store auth.users.id as TEXT (UUIDs fit).
-- Run this in the Supabase SQL editor. pgvector is used for RAG.

create extension if not exists vector;

-- Per-user interview context (Phase 1 minimal; resume_text feeds future RAG)
create table if not exists profiles (
    user_id text primary key,                 -- auth.users.id as text
    target_role text,
    seniority text,
    resume_text text,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- Guests: anonymous users get a limited number of free attempts before login
create table if not exists guests (
    guest_token text primary key,
    attempt_count int not null default 0,
    interview_count int not null default 0,   -- separate cap for full mock interviews
    claimed_by_user_id text,                  -- set when a guest signs up and claims attempts
    created_at timestamptz default now()
);
-- Added after initial release; idempotent for pre-existing guests tables.
alter table guests add column if not exists interview_count int not null default 0;

-- Interview questions (generated by the app, provided by the user, or from a bank)
create table if not exists questions (
    id uuid primary key default gen_random_uuid(),
    owner_user_id text,                       -- null for global/bank questions
    qtype text not null,                      -- 'behavioral' | 'technical'
    prompt text not null,
    source text not null default 'generated', -- 'generated' | 'user' | 'bank'
    meta jsonb default '{}',                  -- leetcode #, difficulty, topic, role
    created_at timestamptz default now()
);

-- An answer attempt (one recording). Owned by a user OR a guest.
create table if not exists attempts (
    id uuid primary key default gen_random_uuid(),
    user_id text,                             -- auth.users.id; null for guest
    guest_token text,                         -- set for guest attempts; null after claim
    question_id uuid references questions(id) on delete set null,
    title text not null default 'Untitled Attempt',
    audio_path text,                          -- storage object path (private bucket)
    transcript_text text,
    duration_sec float,
    status text not null default 'pending',
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    constraint attempts_owner_chk check (user_id is not null or guest_token is not null)
);
-- Per-attempt recording budget (3 min behavioral/coding, 5 min project/design).
alter table attempts add column if not exists max_duration_sec int;

-- Delivery metrics (filler/pace/pause analysis) — one row per attempt
create table if not exists delivery_metrics (
    attempt_id uuid primary key references attempts(id) on delete cascade,
    total_fillers int default 0,
    fillers_per_minute float default 0,
    words_per_minute float default 0,
    avg_pause_sec float default 0,
    avg_pause_before_filler_sec float default 0,
    avg_pause_elsewhere_sec float default 0,
    total_pauses int default 0,
    long_pauses int default 0,
    pauses_per_minute float default 0,
    total_pause_sec float default 0,
    long_pause_filler_pct float default 0,
    transition_filler_pct float default 0,
    position_breakdown jsonb default '{}',
    filler_breakdown jsonb default '{}',
    tag_breakdown jsonb default '{}',
    pauses jsonb default '[]'
);

-- Pause metrics added after initial release; add to pre-existing tables idempotently.
alter table delivery_metrics add column if not exists total_pauses int default 0;
alter table delivery_metrics add column if not exists long_pauses int default 0;
alter table delivery_metrics add column if not exists pauses_per_minute float default 0;
alter table delivery_metrics add column if not exists total_pause_sec float default 0;
alter table delivery_metrics add column if not exists pauses jsonb default '[]';

create table if not exists transcript_words (
    id bigserial primary key,
    attempt_id uuid references attempts(id) on delete cascade,
    word text not null,
    start_time float not null,
    end_time float not null,
    word_index int not null
);

create table if not exists fillers (
    id bigserial primary key,
    attempt_id uuid references attempts(id) on delete cascade,
    word text not null,
    start_time float not null,
    end_time float not null,
    word_index int not null,
    context_text text,
    clip_path text,
    sentence_position text,
    is_transition_related boolean default false,
    tag text,
    tag_reason text,
    topic text
);

-- Scorecards (rubric evaluation of an attempt) — Phase 2/3
create table if not exists scorecards (
    id uuid primary key default gen_random_uuid(),
    attempt_id uuid references attempts(id) on delete cascade,
    rubric text not null,                     -- 'star' | 'technical'
    overall_summary text,
    overall_score float,
    dimensions jsonb default '[]',            -- [{dimension, score, rationale, evidence, suggestion}]
    created_at timestamptz default now()
);

-- Mock interview sessions — a guided multi-question session with dynamic follow-ups.
-- Each turn (main question or follow-up) is one attempt; this row groups them via an
-- append-only turns log. Heavy per-turn data lives in attempts/scorecards.
create table if not exists interview_sessions (
    id uuid primary key default gen_random_uuid(),
    user_id text,                             -- auth.users.id; null for guest
    guest_token text,                         -- set for guest sessions
    mode text not null,                       -- 'behavioral' | 'technical'
    status text not null default 'active',    -- 'active' | 'complete' | 'abandoned'
    config jsonb default '{}',                -- role, seniority, section
    plan jsonb default '[]',                  -- immutable ordered main-question specs
    turns jsonb default '[]',                 -- append-only [{turn_id, plan_index, is_followup, ...}]
    report jsonb,                             -- null until the interview is finished
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    constraint interview_owner_chk check (user_id is not null or guest_token is not null)
);

-- RAG corpus: chunks of reference coaching material, with embeddings.
-- vector(768) matches the default embedder (local BAAI/bge-base-en-v1.5 OR Gemini
-- text-embedding-004); change the dimension if you swap to a different-size model.
create table if not exists kb_documents (
    id uuid primary key default gen_random_uuid(),
    kind text not null,                       -- 'behavioral_guidance'
    ref text,                                 -- source filename / topic key
    content text not null,
    embedding vector(768),
    meta jsonb default '{}',
    created_at timestamptz default now()
);

-- Legacy single-row budget ledger (superseded by api_usage_daily below; kept so
-- older code/queries don't break). New spend tracking uses api_usage_daily.
create table if not exists api_budget (
    id int primary key default 1,
    spent_usd float default 0,
    cap_usd float default 3.0,
    updated_at timestamptz default now()
);
insert into api_budget (id, spent_usd, cap_usd) values (1, 0, 3.0)
on conflict (id) do nothing;

-- Durable, per-(day, subject) spend ledger — the source of truth for the daily
-- budget caps (services/budget.py). Date-bucketed so it "resets" at UTC midnight
-- automatically. subject is 'global' | 'user:<clerk_id>' | 'ip:<addr>'. Required
-- on ephemeral-disk hosts (Render) where a local file would reset on restart.
create table if not exists api_usage_daily (
    day date not null,
    subject text not null,
    spent_usd double precision not null default 0,
    primary key (day, subject)
);

-- Atomic "add cost and return new total" used by budget.record_cost(). SECURITY
-- INVOKER (default): callers without INSERT privilege on api_usage_daily (i.e.
-- the public anon key, after rls.sql) cannot use it — only the service-role
-- backend can. Returns the new running total for (day, subject).
create or replace function increment_api_usage(
    p_day date,
    p_subject text,
    p_cost double precision
) returns double precision
language sql
as $$
    insert into api_usage_daily (day, subject, spent_usd)
    values (p_day, p_subject, p_cost)
    on conflict (day, subject) do update
        set spent_usd = api_usage_daily.spent_usd + excluded.spent_usd
    returning spent_usd;
$$;

-- Indexes
create index if not exists idx_attempts_user_id on attempts(user_id);
create index if not exists idx_attempts_guest_token on attempts(guest_token);
create index if not exists idx_interviews_user_id on interview_sessions(user_id);
create index if not exists idx_interviews_guest_token on interview_sessions(guest_token);
create index if not exists idx_attempts_created_at on attempts(created_at desc);
create index if not exists idx_scorecards_attempt_id on scorecards(attempt_id);
create index if not exists idx_fillers_attempt_id on fillers(attempt_id);
create index if not exists idx_transcript_words_attempt_id on transcript_words(attempt_id);
create index if not exists idx_questions_owner on questions(owner_user_id);
-- pgvector ANN index for RAG similarity search.
-- HNSW (not ivfflat): ivfflat with a small corpus + a strict meta.bucket filter probes too
-- few clusters and under-returns (fewer than match_count, sometimes missing the best chunks).
-- HNSW gives high recall out of the box, needs no probe tuning, and scales. Exact-scan is
-- also fine below ~10k rows if you prefer to drop the index entirely.
create index if not exists idx_kb_embedding on kb_documents
  using hnsw (embedding vector_cosine_ops);

-- Top-k cosine match for RAG retrieval (called by kb_store.retrieve_similar via RPC).
create or replace function match_kb_documents(
    query_embedding vector(768),
    match_count int default 4,
    filter_kind text default null,
    filter_bucket text default null
)
returns table (id uuid, kind text, ref text, content text, meta jsonb, similarity float)
language sql stable as $$
    select id, kind, ref, content, meta,
           1 - (embedding <=> query_embedding) as similarity
    from kb_documents
    where embedding is not null
      and (filter_kind is null or kind = filter_kind)
      and (filter_bucket is null or meta->>'bucket' = filter_bucket)
    order by embedding <=> query_embedding
    limit match_count;
$$;

-- Full-text index for the keyword (sparse) half of hybrid retrieval.
create index if not exists idx_kb_content_fts
  on kb_documents using gin (to_tsvector('english', content));

-- HYBRID retrieval: dense pgvector + Postgres full-text, fused with Reciprocal Rank
-- Fusion (RRF). Each retriever contributes 1/(rrf_k + rank); missing side contributes 0.
-- Sparse half degrades to nothing on an empty tsquery, so this reduces to dense-only for
-- keyword-less queries. Called by kb_store.retrieve_similar via RPC.
create or replace function match_kb_documents_hybrid(
    query_embedding vector(768),
    query_text text,
    match_count int default 4,
    filter_kind text default null,
    filter_bucket text default null,
    pool int default 30,
    rrf_k int default 60
)
returns table (id uuid, kind text, ref text, content text, meta jsonb, score float)
language sql stable as $$
    with dense as (
        select d.id,
               row_number() over (order by d.embedding <=> query_embedding) as rnk
        from kb_documents d
        where d.embedding is not null
          and (filter_kind is null or d.kind = filter_kind)
          and (filter_bucket is null or d.meta->>'bucket' = filter_bucket)
        order by d.embedding <=> query_embedding
        limit pool
    ),
    sparse as (
        select d.id,
               row_number() over (
                   order by ts_rank(to_tsvector('english', d.content),
                                    websearch_to_tsquery('english', query_text)) desc
               ) as rnk
        from kb_documents d
        where (filter_kind is null or d.kind = filter_kind)
          and (filter_bucket is null or d.meta->>'bucket' = filter_bucket)
          and to_tsvector('english', d.content) @@ websearch_to_tsquery('english', query_text)
        order by ts_rank(to_tsvector('english', d.content),
                         websearch_to_tsquery('english', query_text)) desc
        limit pool
    ),
    fused as (
        select coalesce(dense.id, sparse.id) as id,
               coalesce(1.0 / (rrf_k + dense.rnk), 0) +
               coalesce(1.0 / (rrf_k + sparse.rnk), 0) as score
        from dense
        full outer join sparse on dense.id = sparse.id
    )
    select d.id, d.kind, d.ref, d.content, d.meta, f.score
    from fused f
    join kb_documents d on d.id = f.id
    order by f.score desc
    limit match_count;
$$;

-- ---------------------------------------------------------------------------
-- New-user profile row. auth.users.id is a uuid; profiles.user_id is text so
-- existing guest-era rows stay valid. The function is security definer so the
-- auth admin can insert into public.profiles.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id)
  values (new.id::text)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- RLS note: The FastAPI backend is the ONLY Supabase client. It holds the
-- service-role key (which bypasses RLS). Identity is a verified Supabase Auth
-- JWT (or guest token) checked in FastAPI; every query is scoped by that
-- user_id / guest_token. Keep anon/authenticated revoked (see rls.sql).
-- ---------------------------------------------------------------------------
